### PR TITLE
fix: change minor thematic issues

### LINKED ISSUE #60: fix search box width on home screen on mobile

### PR DESCRIPTION
**Pull request by bhajneet**
### Summary of PR
fixes various minor issues with css theming -- surprised so many of these exist, i'm sure learning more about ifm and having that project mature more in the future will help later

### Tests for unexpected behavior
- light vs dark theme
- desktop vs mobile views

### Time spent on PR
2 hours

### Linked issues
Fix #60

### CODE REVIEW

**Review by saihaj — COMMENTED** [review]
Is it possible to make track dark color and scroll bar of lighter color in dark mode?
image

**Comment by bhajneet** [comment]
I don't have a mac to figure that out. Please try on your own, sorry.

**Comment by saihaj** [comment]
I will explore that. How does it look on windows?

**Review by saihaj — APPROVED** [review]
Thanks!

**Comment by bhajneet** [comment]
> 
> 
> I will explore that. How does it look on windows?

image

**Review by saihaj — APPROVED** [review]

**Pull request merged**
