### PR TITLE
fix: broken links related #51

### PR DESCRIPTION
**Pull request by saihaj**
Introduced in #51 when tutorial guides were moved.﻿

### CODE REVIEW

**Comment by bhajneet** [comment]
Perhaps we should convert all links to static? Then if we move a doc, any references to that doc can be easily search and replaced, whereas with relative we have to manually check every doc and configure the right number of directory changes lol

Again, not sure how much we'll shuffle docs around in the future, but if we do, it's a real hassle without static links

See how I did the imgs, that's how we can do all article links too, directly inline after importing one line.

**Comment by saihaj** [comment]
I didn’t knew if it was possible to make links static.  I think we should make links static. Maybe we can also add redirects to make old paths work if needed in some cases

**Comment by bhajneet** [comment]
> 
> 
> I didn’t knew if it was possible to make links static. I think we should make links static. Maybe we can also add redirects to make old paths work if needed in some cases

Okay, please close this PR and open an issue and assign me. I'll get it done sometime today or tomorrow.

**Comment by saihaj** [comment]
Closing in favor of  #54

**Pull request closed without merging**
