### PR TITLE
feat: add initial theming

### PR DESCRIPTION
**Pull request by bhajneet**
### Summary of PR
Themes the docusaurus inline with Avani brand

Light Example:
image

Dark Example:
image

### Tests for unexpected behavior
- scrolling different pages
- I know there is an issue with codeblocks in light theme, have PR'd upstream hopefully for a better theme

### Time spent on PR
5 hours

### Reviewers
@

### CODE REVIEW

**Review by saihaj — CHANGES_REQUESTED** [review]
This looks amazing!!! 

On light theme the navigation toggle is harder to see
image

**Comment by bhajneet** [comment]
I forgot to test with mobile. Let me do that now, should not take more than 10 mins.

**Review by saihaj — COMMENTED** [review]
Is it possible to bring `#` to left?
image

**Comment by AkalUstat** [comment]
wow this looks amazing :) !

**Comment by bhajneet** [comment]
Idk, maybe you can file an issue for that cosmetic issue lol

**Review by saihaj — APPROVED** [review]

**Pull request merged**
